프라미스 핸들러 `.then/catch/finally`는 항상 비동기적으로 실행 된다

프라미스가 즉시 이행되더라도 `.then/catch/finally` 아래에 있는 코드는 이 핸들러들이 실행되기 전에 실행 됨

```js
let promise = Promise.resolve();

promise.then(() => alert("프라미스 성공!"));

alert("코드 종료"); // 얼럿 창이 가장 먼저 뜹니다.
```

왜 `.then`이 나중에 트리거가 되었을까? 프라미스는 즉시 이행상태가 되었는데

### 마이크로태스크 큐
비동기 작업을 처리하려면 적절한 관리가 필요합니다. 이를 위해 ECMA에선 `PromiseJobs`라는 내부 큐(internal queue)를 명시함. V8 엔진에선 이를 '마이크로태스크 큐(microtask queue)'라고 부르기 때문에 이 용어가 좀 더 선호된다.

명세서의 설명을 살펴보자
- 마이크로태스크 큐는 먼저 들어온 작업을 먼저 실행(FIFO)
- 실행할 것이 아무것도 남아있지 않을 때만 마이크로태스크 큐에 있는 작업이 실행되기 시작
![프라미스 마이크로태스크큐.png](./images/프라미스%20마이크로태스크큐.png)
요약하자면, 어떤 프라미스가 준비되었을 때 이 프라미스의 `.then/catch/finally` 핸들러가 큐에 들어간다고 생가하면 된다. 이때 핸들러들은 여전히 실행되지 않는다. 현재 코드에서 자유로운 상태가 되었을 때에서야 js엔진은 큐에서 작업을 꺼내 실행함

### 처리되지 못한 거부
이제 자바스크립트 엔진이 어떻게 처리되지 못한 거부를 찾는지 정확히 알 수 있음

**'처리되지 못한 거부'는 마이크로태스크 큐 끝에서 프라미스 에러가 처리되지 못할 때 발생**
```js
let promise = Promise.reject(new Error("프라미스 실패!"));
promise.catch(err => alert('잡았다!'));

// 에러가 잘 처리되었으므로 실행되지 않습니다.
window.addEventListener('unhandledrejection', event => alert(event.reason));
```

 `.catch`를 추가해주는 걸 잊은 경우, 엔진은 마이크로태스크 큐가 빈 이후에 `unhandledrejection` 이벤트를 트리거.
```js
let promise = Promise.reject(new Error("프라미스 실패!"));

// 프라미스 실패!
window.addEventListener('unhandledrejection', event => alert(event.reason));
```


그런데 만약 아래와 같이 `setTimeout`을 이용해 에러를 나중에 처리하면 어떤 일이 생길까요?
```js
let promise = Promise.reject(new Error("프라미스 실패!"));
setTimeout(() => promise.catch(err => alert('잡았다!')), 1000);

// Error: 프라미스 실패!
window.addEventListener('unhandledrejection', event => alert(event.reason));
```
프라미스 실패가 먼저 잡았다가 나중에 출력되는 걸 확인할 수 있다

마이크로태스크 큐에 대해 몰랐다면 "에러를 잡았는데도 왜 `unhandledrejection` 핸들러가 실행되는 거지?"라는 의문을 가졌을 것.

`unhandledrejection`은 마이크로태스크 큐에 있는 작업 모두가 완료되었을 때 생성됩니다. 엔진은 프라미스들을 검사하고 이 중 하나라도 ‘거부(rejected)’ 상태이면 `unhandledrejection` 핸들러를 트리거 하죠. 이로써 앞선 의문이 자연스레 해결되었습니다.

위 예시를 실행하면 `setTimeout`을 사용해 추가한 `.catch` 역시 트리거 됩니다. 다만 `.catch`는 `unhandledrejection`이 발생한 이후에 트리거 되므로 `프라미스 실패!`가 출력

나만의 언어로 비유:
>키오스크에서 주문을 하고 음식에 대한 주문벨을 받는다. 
>손님은 이 주문벨을 가지고 음식이 성공했을경우(then), 실패했을경우(catch), 성공하든 아니든 할 행동(finally)를 지정할 수 있다
>이때 행동들은 바로 수행이 되는게 아닌 다른 일을 모두 마친 후에 실행된다(음식이 준비 됐다고 알림이 와도 한가해졌을 때 실행 됨)